spring:
  application:
    name: SoftCore
  main:
    banner-mode: log
  profiles:
    active: dev
  messages:
    basename: messages
    encoding: UTF-8

server:
  port: 8081

logging:
  file:
    path: logs
  level:
    root: info